export const SAVE_COMMISSION_INITIATED = "SAVE_COMMISSION_INITIATED";
export const SAVE_COMMISSION_SUCCESS = "SAVE_COMMISSION_SUCCESS";
export const SAVE_COMMISSION_ERROR = "SAVE_COMMISSION_ERROR";

export const GET_COMMISSION_INITIATED = "GET_COMMISSION_INITIATED";
export const GET_COMMISSION_SUCCESS = "GET_COMMISSION_SUCCESS";
export const GET_COMMISSION_ERROR = "GET_COMMISSION_ERROR";

export const DELETE_COMMISSION_INITIATED = "DELETE_COMMISSION_INITIATED";
export const DELETE_COMMISSION_SUCCESS = "DELETE_COMMISSION_SUCCESS";
export const DELETE_COMMISSION_ERROR = "DELETE_COMMISSION_ERROR";

export const SAVE_COMMISSION_MANAGE_INITIATED = "SAVE_COMMISSION_MANAGE_INITIATED";
export const SAVE_COMMISSION_MANAGE_SUCCESS = "SAVE_COMMISSION_MANAGE_SUCCESS";
export const SAVE_COMMISSION_MANAGE_ERROR = "SAVE_COMMISSION_MANAGE_ERROR";

export const GET_COMMISSION_MANAGE_INITIATED = "GET_COMMISSION_MANAGE_INITIATED";
export const GET_COMMISSION_MANAGE_SUCCESS = "GET_COMMISSION_MANAGE_SUCCESS";
export const GET_COMMISSION_MANAGE_ERROR = "GET_COMMISSION_MANAGE_ERROR";

export const GET_COMMISSION_BY_ID_INITIATED = "GET_COMMISSION_BY_ID_INITIATED";
export const GET_COMMISSION_BY_ID_SUCCESS = "GET_COMMISSION_BY_ID_SUCCESS";
export const GET_COMMISSION_BY_ID_ERROR = "GET_COMMISSION_BY_ID_ERROR";