export const SAVE_PROMOCODE_INITIATED = "SAVE_PROMOCODE_INITIATED";
export const SAVE_PROMOCODE_SUCCESS = "SAVE_PROMOCODE_SUCCESS";
export const SAVE_PROMOCODE_ERROR = "SAVE_PROMOCODE_ERROR";

export const GET_PROMO_INITIATED = "GET_PROMO_INITIATED";
export const GET_PROMO_SUCCESS = "GET_PROMO_SUCCESS";
export const GET_PROMO_ERROR = "GET_PROMO_ERROR";

export const DELETE_PROMO_INITIATED = "DELETE_PROMO_INITIATED";
export const DELETE_PROMO_SUCCESS = "DELETE_PROMO_SUCCESS";
export const DELETE_PROMO_ERROR = "DELETE_PROMO_ERROR";
