export const SAVE_LOGINIMAGE_INITIATED = "SAVE_LOGINIMAGE_INITIATED";
export const SAVE_LOGINIMAGE_SUCCESS = "SAVE_LOGINIMAGE_SUCCESS";
export const SAVE_LOGINIMAGE_ERROR = "SAVE_LOGINIMAGE_ERROR";

export const GET_LOGINIMAGES_INITIATED = "GET_LOGINIMAGES_INITIATED";
export const GET_LOGINIMAGES_SUCCESS = "GET_LOGINIMAGES_SUCCESS";
export const GET_LOGINIMAGES_ERROR = "GET_LOGINIMAGES_ERROR";

export const DELETE_LOGINIMAGES_INITIATED = "DELETE_LOGINIMAGES_INITIATED";
export const DELETE_LOGINIMAGES_SUCCESS = "DELETE_LOGINIMAGES_SUCCESS";
export const DELETE_LOGINIMAGES_ERROR = "DELETE_LOGINIMAGES_ERROR";

export const SAVE_TESTIMONIAL_INITIATED = "SAVE_TESTIMONIAL_INITIATED";
export const SAVE_TESTIMONIAL_SUCCESS = "SAVE_TESTIMONIAL_SUCCESS";
export const SAVE_TESTIMONIAL_ERROR = "SAVE_TESTIMONIAL_ERROR";

export const DELETE_TESTIMONIAL_INITIATED = "DELETE_TESTIMONIAL_INITIATED";
export const DELETE_TESTIMONIAL_SUCCESS = "DELETE_TESTIMONIAL_SUCCESS";
export const DELETE_TESTIMONIAL_ERROR = "DELETE_TESTIMONIAL_ERROR";

export const GET_TESTIMONIAL_INITIATED = "GET_TESTIMONIAL_INITIATED";
export const GET_TESTIMONIAL_SUCCESS = "GET_TESTIMONIAL_SUCCESS";
export const GET_TESTIMONIAL_ERROR = "GET_TESTIMONIAL_ERROR";

export const GET_TESTIMONIAL_BY_ID_INITIATED =
  "GET_TESTIMONIAL_BY_ID_INITIATED";
export const GET_TESTIMONIAL_BY_ID_SUCCESS = "GET_TESTIMONIAL_BY_ID_SUCCESS";
export const GET_TESTIMONIAL_BY_ID_ERROR = "GET_TESTIMONIAL_BY_ID_ERROR";

export const SAVE_OFFERS_INITIATED = "SAVE_OFFERS_INITIATED";
export const SAVE_OFFERS_SUCCESS = "SAVE_OFFERS_SUCCESS";
export const SAVE_OFFERS_ERROR = "SAVE_OFFERS_ERROR";

export const GET_OFFERLIST_INITIATED = "GET_OFFERLIST_INITIATED";
export const GET_OFFERLIST_SUCCESS = "GET_OFFERLIST_SUCCESS";
export const GET_OFFERLIST_ERROR = "GET_OFFERLIST_ERROR";

export const GET_OFFER_BY_ID_INITIATED = "GET_OFFER_BY_ID_INITIATED";
export const GET_OFFER_BY_ID_SUCCESS = "GET_OFFER_BY_ID_SUCCESS";
export const GET_OFFER_BY_ID_ERROR = "GET_OFFER_BY_ID_ERROR";

export const DELETE_OFFER_BY_ID_INITIATED = "DELETE_OFFER_BY_ID_INITIATED";
export const DELETE_OFFER_BY_ID_SUCCESS = "DELETE_OFFER_BY_ID_SUCCESS";
export const DELETE_OFFER_BY_ID_ERROR = "DELETE_OFFER_BY_ID_ERROR";

export const SAVE_CATEGORY_INITIATED = "SAVE_CATEGORY_INITIATED";
export const SAVE_CATEGORY_SUCCESS = "SAVE_CATEGORY_SUCCESS";
export const SAVE_CATEGORY_ERROR = "SAVE_CATEGORY_ERROR";

export const CATEGORY_LIST_INITIATED = "CATEGORY_LIST_INITIATED";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_ERROR = "CATEGORY_LIST_ERROR";

export const SAVE_KNOWLEDGE_INITIATED = "SAVE_KNOWLEDGE_INITIATED";
export const SAVE_KNOWLEDGE_SUCCESS = "SAVE_KNOWLEDGE_SUCCESS";
export const SAVE_KNOWLEDGE_ERROR = "SAVE_KNOWLEDGE_ERROR";

export const KNOWLEDGE_LIST_INITIATED = "KNOWLEDGE_LIST_INITIATED";
export const KNOWLEDGE_LIST_SUCCESS = "KNOWLEDGE_LIST_SUCCESS";
export const KNOWLEDGE_LIST_ERROR = "KNOWLEDGE_LIST_ERROR";

export const KNOWLEDGE_BY_ID_INITIATED = "KNOWLEDGE_BY_ID_INITIATED";
export const KNOWLEDGE_BY_ID_SUCCESS = "KNOWLEDGE_BY_ID_SUCCESS";
export const KNOWLEDGE_BY_ID_ERROR = "KNOWLEDGE_BY_ID_ERROR";

export const DELETE_KNOWLEDGE_INITIATED = "DELETE_KNOWLEDGE_INITIATED";
export const DELETE_KNOWLEDGE_SUCCESS = "DELETE_KNOWLEDGE_SUCCESS";
export const DELETE_KNOWLEDGE_ERROR = "DELETE_KNOWLEDGE_ERROR";