export const SAVE_POC_INITIATED = "SAVE_POC_INITIATED";
export const SAVE_POC_SUCCESS = "SAVE_POC_SUCCESS";
export const SAVE_POC_ERROR = "SAVE_POC_ERROR";

export const GET_POC_INITIATED = "GET_POC_INITIATED";
export const GET_POC_SUCCESS = "GET_POC_SUCCESS";
export const GET_POC_ERROR = "GET_POC_ERROR";

export const DELETE_POC_INITIATED = "DELETE_POC_INITIATED";
export const DELETE_POC_SUCCESS = "DELETE_POC_SUCCESS";
export const DELETE_POC_ERROR = "DELETE_POC_ERROR"; 