export const SET_PROSPECT_INITIATED = "SET_PROSPECT_INITIATED";
export const SET_PROSPECT_SUCCESS = "SET_PROSPECT_SUCCESS";
export const SET_PROSPECT_ERROR = "SET_PROSPECT_ERROR";

export const SET_LEAD_INITIATED = "SET_LEAD_INITIATED";
export const SET_LEAD_SUCCESS = "SET_LEAD_SUCCESS";
export const SET_LEAD_ERROR = "SET_LEAD_ERROR";

export const SET_DEMO_INITIATED = "SET_DEMO_INITIATED";
export const SET_DEMO_SUCCESS = "SET_DEMO_SUCCESS";
export const SET_DEMO_ERROR = "SET_DEMO_ERROR";