export const ADD_WITHDARAW_MONEY_INITIATED = "ADD_WITHDARAW_MONEY_INITIATED";
export const ADD_WITHDARAW_MONEY_SUCCESS = "ADD_WITHDARAW_MONEY_SUCCESS";
export const ADD_WITHDARAW_MONEY_ERROR = "ADD_WITHDARAW_MONEY_ERROR";

export const TARANSACTION_HISTORY_INITIATED = "TARANSACTION_HISTORY_INITIATED";
export const TARANSACTION_HISTORY_SUCCESS = "TARANSACTION_HISTORY_SUCCESS";
export const TARANSACTION_HISTORY_ERROR = "TARANSACTION_HISTORY_ERROR";

export const GET_PARTNER_TRANSACTION_INITIATED = "GET_PARTNER_TRANSACTION_INITIATED";
export const GET_PARTNER_TRANSACTION_SUCCESS = "GET_PARTNER_TRANSACTION_SUCCESS";
export const GET_PARTNER_TRANSACTION_ERROR = "GET_PARTNER_TRANSACTION_ERROR";

export const GET_CURRENTBALANCE_INITIATED = "GET_CURRENTBALANCE_INITIATED";
export const GET_CURRENTBALANCE_SUCCESS = "GET_CURRENTBALANCE_SUCCESS";
export const GET_CURRENTBALANCE_ERROR = "GET_CURRENTBALANCE_ERROR";

export const GET_WALLET_DATA_ID_INITIATED = "GET_WALLET_DATA_ID_INITIATED";
export const GET_WALLET_DATA_ID_SUCCESS = "GET_WALLET_DATA_ID_SUCCESS";
export const GET_WALLET_DATA_ID_ERROR = "GET_WALLET_DATA_ID_ERROR";

export const SAVE_WITHDRAW_INITIATED = "SAVE_WITHDRAW_INITIATED";
export const SAVE_WITHDRAW_SUCCESS = "SAVE_WITHDRAW_SUCCESS";
export const SAVE_WITHDRAW_ERROR = "SAVE_WITHDRAW_ERROR";

export const GET_WITHDRAW_LIST_INITIATED = "GET_WITHDRAW_LIST_INITIATED";
export const GET_WITHDRAW_LIST_SUCCESS = "GET_WITHDRAW_LIST_SUCCESS";
export const GET_WITHDRAW_LIST_ERROR = "GET_WITHDRAW_LIST_ERROR";

export const DELETE_WITHDRAW_REQUEST_INITIATED = "DELETE_WITHDRAW_REQUEST_INITIATED";
export const DELETE_WITHDRAW_REQUEST_SUCCESS = "DELETE_WITHDRAW_REQUEST_SUCCESS";
export const DELETE_WITHDRAW_REQUEST_ERROR = "DELETE_WITHDRAW_REQUEST_ERROR";

export const GET_WITHDRAW_REQUESTS_INITIATED = "GET_WITHDRAW_REQUESTS_INITIATED";
export const GET_WITHDRAW_REQUESTS_SUCCESS = "GET_WITHDRAW_REQUESTS_SUCCESS";
export const GET_WITHDRAW_REQUESTS_ERROR = "GET_WITHDRAW_REQUESTS_ERROR";

export const SAVE_WITHDRAW_REQUESTS_INITIATED = "SAVE_WITHDRAW_REQUESTS_INITIATED";
export const SAVE_WITHDRAW_REQUESTS_SUCCESS = "SAVE_WITHDRAW_REQUESTS_SUCCESS";
export const SAVE_WITHDRAW_REQUESTS_ERROR = "SAVE_WITHDRAW_REQUESTS_ERROR";