const PartConst = {
  partners: "Partner's",
  actPartner: " Activate Partner",
  deactPartner: " Deactivate Partner",
  title: "Delete Partner",
  content: "Are you sure you want to",
  yes: "Yes",
  no: "No",
  companyname: "Company Name",
  email: "Email ID",
  mobile: "Mobile No",
  gst: "GST Type",
  gstno: "GstNumber",
  pan: "Pan",
  aadhar: "AadharNumber",
  bank: "Bank Name",
  branch: "Branch Name",
  address: "Address",
  account: "Account Number",
  ifsc: "Ifsc Code",
  pincode: "Pincode",
  state: "State",
  city: "City",
  contactname: "Contact Name",
  designation: "Designation",
  qus: "?",
};
const tabsTitle = ["Basic Details", "Financial Details", "Contact Details"];
export { PartConst, tabsTitle };
