export const SAVE_MEDIA_INITIATED = "SAVE_MEDIA_INITIATED";
export const SAVE_MEDIA_SUCCESS = "SAVE_MEDIA_SUCCESS";
export const SAVE_MEDIA_ERROR = "SAVE_MEDIA_ERROR";

export const GET_MEDIA_INITIATED = "GET_MEDIA_INITIATED";
export const GET_MEDIA_SUCCESS = "GET_MEDIA_SUCCESS";
export const GET_MEDIA_ERROR = "GET_MEDIA_ERROR";

export const DELETE_MEDIA_INITIATED = "DELETE_MEDIA_INITIATED";
export const DELETE_MEDIA_SUCCESS = "DELETE_MEDIA_SUCCESS";
export const DELETE_MEDIA_ERROR = "DELETE_MEDIA_ERROR";