const TabConst = {
  view: "View",
  edit: "Edit",
  wallet: "Wallet",
  prospect: "Prospect",
  leads: "Leads",
  sales: "Sales",
  delete: "Delete",
  cancel: "Cancel",
  download: "Download",
  comment: "Comment",
  status: "Status",
  curPwd: "Current Password",
  entCurPwd: "Enter Current Password",
  newPwd: "New Password",
  entNewPwd: "Enter New Password",
  cunfNewPwd: "Confirm New Password",
  star: "*",
  sr: "#",
  notif: "Notifications",
  no: "No",
  va: "View All",
  email: "Email",
  search: "Search",
  mobile: "Mobile Number",
  address: "Address",
  rem: "Remarks",
  emid: "Email ID",
  cusName: "Customer Name",
  liedName: "Lead Name",
  cusSelect: "Customer Selection",
  lt: "Lead type",
  pro: "Product",
  demo: "Demo",
  sale: "Sale",
  comName: "Company Name",
  ProName: "Prospect Name",
  contDet: "Contact details",
  cont: "Contact",
  leadType: "Lead Type",
  action: "Action",
  number: "Number",
  name: "Name",
  msg: "Message",
  phonNo: "Phone No.",
  entYoNa: "Enter Your Name",
  entYoEmaAdd: "Enter Your Email Address",
  entYoPhoNo: "Enter Your Phone No.",
  saleslist: "Sales List",
  addNeSal: "Add New Sales",
  liceId: "Licence Id",
  subType: "Subscription Type",
  expIn: "Expires in",
  gstType: "GST Type",
  timePer: "Time Period",
  gstno: "GST No.",
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  price: "Price",
  promoCode: "Promo Code",
  discount: "Discount",
  time: "Time",
  amount: "Amount",
  transId: "Transaction ID",
  transType: "Type",
  details: "Details",
  date: "Date",
  partner: "Partner",
  userName: "User Name",
  packageType: "Package Type",
  annual: "Annual ",
  monthly: "Monthly ",
  commission: "Commission",
  creLead: "Create Lead",
  creSales: "Create Sales",
  creMeeting: "Create Meeting",
  activate: "Activate",
  deactivate: "Deactivate",
  type: "Type",
  from: "From",
  publish: "Publish",
  title: "Title",
  pn: "Partner Name",
  numof: "Number of ",
  user: "User",
  create: "CreatedBy",
  modify: "ModifyBy",
  desc: "description",
  icon: "icon",
  approv: "Approv",
  reject: "Reject",
  parAppro: "Partially Approv",
  req: "Request",
  wiDra: "Withdrawal",
  reqAprAmo: "Request approved amount",
  aprAmo: "approved amount",
  pay: "Pay Now",
};
export { TabConst };
