const TabsConst = [
  { name: "Prospect", clsName: "prosAfBF" },
  { name: "Leads", clsName: "leadsAfBF" },
  { name: "Meetings", clsName: "demoAfBF" },
];
const LeadsConst = {
  addNew: "Add New ",
  my: "My ",
  prospect: "Prospect",
  leads: "Leads",
  rec: "Record",
  custnm: "Prospect Name*",
  leadnm: "Lead Name*",
  compnm: "Company Name",
  name: "Name",
  number: "Number",
  mobile: "Mobile Number*",
  emid: "Email ID",
  email: "Email",
  address: "Address",
  save: "Save",
  leadType: "Lead type*",
  product: "Product*",
  rem: "Remark",
  demo: "Demo",
  meeting: "Meeting",
  sale: "Sale",
  search: "Search...",
  adiBul: "Add in Bulk",
  startDate: "Start Date*",
  endDate: "End Date*",
  ProsDate: "Prospect Date",
  Source: "Source",
  contact: "Contact Via",
  active: " Activate ",
  deActive: " Deactivate ",
  content: "Are you sure you want to",
  qus: "?",
  yes: "Yes",
  no: "No",
  meet: "Meetings",
  craLead: "Save & Create Lead",
  craMeeting: "Save & Create Meeting",
};
const contectNames = [
  { id: 1, value: "visit" },
  { id: 2, value: "Email" },
  { id: 3, value: "Call" },
];
const TopRowData = [
  { value: "1", name: "Total Prospect" },
  { value: "3", name: "Active Prospect" },
  { value: "3", name: "Total Leads" },
  { value: "4", name: "Total Meeting" },
];
export { TabsConst, LeadsConst, contectNames, TopRowData };
